$mainMod = SUPER
$altMod = ALT

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, Escape, exit,
bind = $mainMod, E, exec, $terminal $fileManager
bind = $mainMod, Space, exec, $menu
bind = $mainMod, D, togglesplit, # dwindle


bind = $mainMod, S, exec, $HOME/.mynixos/home/dotfiles/shared/scripts/screenshot.sh
bind = $mainMod SHIFT, S, exec, $HOME/.mynixos/home/dotfiles/shared/scripts/screenshotregion.sh 

#move focus with arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

#move focus with vim navigation keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $altMod, f, workspace, 1
bind = $altMod, i, workspace, 2
bind = $altMod, l, workspace, 3
bind = $altMod, m, workspace, 4
bind = $altMod, r, workspace, 5
bind = $altMod, e, workspace, 6
bind = $altMod, p, workspace, 7
bind = $altMod, n, workspace, 8
bind = $altMod, g, workspace, 9
bind = $altMod, 0, workspace, 10

# Move active window to a workspace with altMod + SHIFT + [0-9]
bind = $altMod SHIFT, f, movetoworkspace, 1
bind = $altMod SHIFT, i, movetoworkspace, 2
bind = $altMod SHIFT, l, movetoworkspace, 3
bind = $altMod SHIFT, m, movetoworkspace, 4
bind = $altMod SHIFT, r, movetoworkspace, 5
bind = $altMod SHIFT, e, movetoworkspace, 6
bind = $altMod SHIFT, p, movetoworkspace, 7
bind = $altMod SHIFT, n, movetoworkspace, 8
bind = $altMod SHIFT, g, movetoworkspace, 9
bind = $altMod SHIFT, 0, movetoworkspace, 10


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#reorder windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

#resize windows
bindel = $mainMod CTRL, l, resizeactive, 20 0
bindel = $mainMod CTRL, h, resizeactive, -20 0
bindel = $mainMod CTRL, k, resizeactive, 0 -20
bindel = $mainMod CTRL, j, resizeactive, 0 20

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, $HOME/.mynixos/home/dotfiles/shared/scripts/vol-up.sh
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
